FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY icons.js /usr/share/nginx/html/icons.js
COPY app.js /usr/share/nginx/html/app.js
